name: BSN Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'book-network-ui/**'
      - '.github/workflows/frontend-ci-cd.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'book-network-ui/**'

jobs:
  # ✅ TEST DEL FRONTEND
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'book-network-ui/package-lock.json'

      - name: Install dependencies
        working-directory: ./book-network-ui
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests
        working-directory: ./book-network-ui
        run: npm test -- -- --watch=false --browsers=ChromeHeadless

  # 🚀 DEPLOY AUTOMÁTICO A VERCEL
  deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./book-network-ui